MyBookstore/netzkern.MyBookstore.UI.Web.Mvc/ViewModels/HomeViewModel.cs
using netzkern.MyBookstore.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace netzkern.MyBookstore.UI.Web.Mvc.ViewModels
{
    public class HomeViewModel
    {
        public Product BestsellerBook { get; set; }
        public IEnumerable<Product> RelatedBookSet { get; set; }
    }
}

MyBookstore/netzkern.MyBookstore.UI.Web.Mvc/Controllers/CartController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using netzkern.MyBookstore.BusinessLogic;
using netzkern.MyBookstore.Model;

namespace netzkern.MyBookstore.UI.Web.Mvc.Controllers
{
    public class CartController : Controller                              
    {
        ProductService _productService;

        public CartController()
        {
            _productService = new ProductService();
        }

        public ActionResult Index()                                 
        {
            return View();
        }

        public ActionResult Buy(int id)                         
        {
           Product product =  _productService.LoadOneProduct(id);

            if (Session["cart"] == null)
            {
                List<CartItem> cart = new List<CartItem>();
                cart.Add(new CartItem { Product = product, Quantity = 1 });
                Session["cart"] = cart;
            }
            else
            {
                List<CartItem> cart = (List<CartItem>)Session["cart"];
                int index = isExist(id);                                       
                if (index != -1)
                {
                    cart[index].Quantity++;
                }
                else
                {
                    cart.Add(new CartItem { Product = product, Quantity = 1 });   
                }
                Session["cart"] = cart;                             
            }
            return RedirectToAction("Index");  
        }

        public ActionResult Remove(int id)                                 
        {
            List<CartItem> cart = (List<CartItem>)Session["cart"];
            int index = isExist(id);             
            cart.RemoveAt(index);    
            Session["cart"] = cart;   
            return RedirectToAction("Index"); 
        }

        private int isExist(int id)              
        {
            List<CartItem> cart = (List<CartItem>)Session["cart"];                   
            for( int i = 0; i < cart.Count; i++ )       
            {
                if (cart[i].Product.Id == id)
                    return i;
            }
            return -1;
        }
    }
}

MyBookstore/netzkern.MyBookstore.UI.Web.Mvc/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using netzkern.MyBookstore.BusinessLogic;
using netzkern.MyBookstore.Model;
using netzkern.MyBookstore.UI.Web.Mvc.ViewModels;
using AutoMapper;

namespace netzkern.MyBookstore.UI.Web.Mvc.Controllers
{
    public class HomeController : Controller
    {
        ProductService _productService;
        public HomeController()
        {
            _productService = new ProductService();
        }

        public ActionResult Index()
        {
            HomeViewModel model = new HomeViewModel()
            {
                RelatedBookSet = new List<Product>()
            };

            var products = this._productService.LoadRelatedProducts(3);
            var bestsellerBook = this._productService.LoadOneProduct(1009);

            if (products != null)
            {
                model = Mapper.Map<IEnumerable<Product>, HomeViewModel>(products);
            }
            if (bestsellerBook != null)
            {
                Mapper.Map(bestsellerBook, model);
            }

            return View(model);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";
            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MyBookstore/netzkern.MyBookstore.UI.Web.Mvc/Controllers/ProductController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using netzkern.MyBookstore.BusinessLogic;
using netzkern.MyBookstore.Model;

namespace netzkern.MyBookstore.UI.Web.Mvc.Controllers
{
    public class ProductController : Controller
    {
        ProductService _productService;

        public ProductController()
        {
            _productService = new ProductService();
        }

        public ActionResult Index( string typeSort = "Titel ASC" )
        {
            List<Product> products = _productService.LoadSortedProducts(typeSort);

            ViewBag.products = products;                                
            return View(products);                   
        }

        public ActionResult DetailView(int id)
        {
            Product product = _productService.LoadOneProduct(id);

            ViewBag.product = product;                                  
            return View(product);                                       
        }
    }
}

MyBookstore/netzkern.MyBookstore.UI.Web.Mvc/Controllers/SignInController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using netzkern.MyBookstore.BusinessLogic;
using netzkern.MyBookstore.Model;

namespace netzkern.MyBookstore.UI.Web.Mvc.Controllers
{
    public class SignInController : Controller
    {
        UserService _userService;

        public SignInController()
        {
            _userService = new UserService();
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult LogIn()
        {
            return View();
        }

        public ActionResult Register()
        {
            return View();
        }

        public ActionResult LogOut()
        {
            Session["userId"] = null;
            Session["userFirstName"] = null;
            Session["userLastName"] = null;

            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Register(User model)
        {
            if (ModelState.IsValid)
            {
                _userService.CreateUser(model);

                ViewBag.texts = "Du hast dich erfolgreich regestriert. Meld dich nun an.";
                return RedirectToAction("LogIn");
            }

            ViewBag.texts = "Es ist etwas schief gelaufen. Bitte überprüfe ob du alle Felder korrekt ausgefüllt hast und versuche es nochmal.";
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult LogIn(User model)
        {
            var user = _userService.LoadUser(model.EmailAddress);

            if (model.EmailAddress == user.EmailAddress && user.Password == user.Password)
            {
                Session["userId"] = user.Id;
                Session["userFirstName"] = user.FirstName;
                Session["userLastName"] = user.LastName;
                ViewBag.texts = "";
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ViewBag.texts = "Email Addresse oder Passwort stimmen nicht. Bitte versuche es normal.";
                return View();
            }
        }
    }
}

MyBookstore/netzkern.MyBookstore.UI.Web.Mvc/Views/Cart/Index.cshtml
@using netzkern.MyBookstore.Model

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Cart</title>
</head>
<body>
    <br>
    <h2>Warenkorb</h2>
    <br>
    @if ((List<CartItem>)Session["cart"] != null)                    
    {
        <table class="table table-hover">
            <tr class="table-dark">
                <th>Option</th>
                <th>Titel</th>
                <th></th>
                <th>Preis</th>
                <th>Anzahl</th>
                <th>Zwischensumme</th>
            </tr>

            @foreach (CartItem item in (List<CartItem>)Session["cart"])
            {
                <tr class="table-light">
                    <td>
                        <a href="@Url.Action("Remove", "Cart", new { id = item.Product.Id })">
                            <button type="button" class="btn btn-outline-warning btn-sm">
                                Entfernen
                            </button>
                        </a>
                    </td>
                    <td>@item.Product.Title</td>
                    <td><img src="~/Content/Images/@item.Product.Photo" width="60" /></td>
                    <td>@item.Product.Price €</td>
                    <td>@item.Quantity</td>
                    <td>@(item.Product.Price * item.Quantity) €</td>
                </tr>
            }
            <tr class="table-dark">
                <td align="right" colspan="6">Summe</td>
                <td>
                    @{
                        List<CartItem> cart = (List<CartItem>)Session["cart"];
                        var total = cart.Sum(item => item.Product.Price * item.Quantity);      
                    }
                    @total
                </td>
            </tr>
        </table>
    }
    else
    {
        <div class="jumbotron">
            <h4>Ihr Warenkorb ist zurzeit leer.</h4>
            <a href="@Url.Action("Index", "Product")"><p class="text-warning">Stöbern Sie jetzt im Sortiment.</p></a>
        </div>

    }

    <br>
    <a href="@Url.Action("Index", "Product")">
        <button type="button" class="btn btn-warning disabled">
            Weiter einkaufen
        </button>
    </a>
</body>
</html>

MyBookstore/netzkern.MyBookstore.UI.Web.Mvc/Views/Home/About.cshtml
@{
    ViewBag.Title = "Info";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Diese Seite befindet sich noch in der Entwicklung.</p>

MyBookstore/netzkern.MyBookstore.UI.Web.Mvc/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Kontakt";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    Katharina Rabanus<br />
    Lischkestr. 8<br />
</address>

<address>
    <strong>Support & Marketing:</strong>   <a href="rabanuskatharina@gmail.com">rabanuskatharina@gmail.com</a>
</address>

MyBookstore/netzkern.MyBookstore.UI.Web.Mvc/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Startseite";
}

@using netzkern.MyBookstore.Model
@model netzkern.MyBookstore.UI.Web.Mvc.ViewModels.HomeViewModel

<div class="jumbotron">
    @Html.Partial("_BestsellerBook", Model.BestsellerBook)
</div>

<div class="row">
    <br>
    <h2>Weitere Empfehlungen</h2>
</div>
<div class="row">
    @Html.Partial("_RelatedBookSet", Model.RelatedBookSet)
</div>

MyBookstore/netzkern.MyBookstore.UI.Web.Mvc/Views/Home/_BestsellerBook.cshtml
@using netzkern.MyBookstore.Model
@model Product

<p class="text-warning">Empfehlung des Tages:</p>
<h2>@Model.Title</h2>
<div class="row">
    <div class="col-md-8">
        <p>@Model.Content</p>
        <a href="@Url.Action("DetailView", "Product", new { id = 10 })">
            <button type="button" class="btn btn-outline-warning">Erfahre mehr &raquo;</button>
        </a>
    </div>
    <div class="col-md-4">
        <a href="@Url.Action("DetailView", "Product", new { id = 10 })">
            <img src="~/Content/Images/05.jpeg" width="200" />
        </a>
    </div>
</div>

MyBookstore/netzkern.MyBookstore.UI.Web.Mvc/Views/Home/_RelatedBookSet.cshtml
@using netzkern.MyBookstore.Model
@model IEnumerable<Product>

    @foreach (Product product in Model)
    {
        <div class="card border-light mb-3" style="max-width: 20rem;">
            <div class="card-body">
                <h5 class="card-title">@product.Title</h5>
                <a href="@Url.Action("DetailView", "Product", new { id = product.Id })">
                    <img src="~/Content/Images/@product.Photo" width="100" />
                </a>
            </div>
            <div>
                <a href="@Url.Action("DetailView", "Product", new { id = product.Id })">
                    <button type="button" class="btn btn-outline-warning btn-sm">
                        Erfahre mehr &raquo;
                    </button>
                </a>
            </div>
        </div>
    }

MyBookstore/netzkern.MyBookstore.UI.Web.Mvc/Views/Product/DetailView.cshtml
@using netzkern.MyBookstore.Model

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>DetailView</title>
</head>
<body>
    <div class="jumbotron">
        <div class="row">
            <div class="col">
                <img src="~/Content/Images/@ViewBag.product.Photo" width="250" />
            </div>
            <div class="col-md-5">
                <div class="row">
                    <h4>@ViewBag.product.Author</h4>
                </div>
                <div class="row">
                    <h3>@ViewBag.product.Titel</h3>
                </div>
                <div class="row">
                    <br>
                    <p>@ViewBag.product.Content</p>
                </div>
                <div class="row">

                </div>
            </div>
            <div class="col-md-3" align="center">
                <div class="row">
                    <p class="text-warning"><b>@ViewBag.product.Price €</b></p>
                </div>
                <div class="row">
                    <a href="@Url.Action("Buy", "Cart", new { id = ViewBag.product.Id })">
                        <button type="button" class="btn btn-warning disabled">
                            Kaufen
                        </button>
                    </a>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

MyBookstore/netzkern.MyBookstore.UI.Web.Mvc/Views/Product/Index.cshtml
@using netzkern.MyBookstore.Model

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div class="col">
        <table class="table table-hover">
            <tr class="table-light">
                <td>
                    <h2>Products List</h2>
                </td>
                <td>
                    <div class="nav-item dropdown show">
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Sortieren nach</a>
                        <div class="dropdown-menu show" style="position: absolute; transform: translate3d(0px, 37px, 0px); top: 0px; left: 0px; will-change: transform;" x-placement="bottom-start">
                            <a class="dropdown-item" href="@Url.Action("Index", "Product", new { typeSort = "Titel ASC" })">Titel A-Z</a>
                            <a class="dropdown-item" href="@Url.Action("Index", "Product", new { typeSort = "Titel DESC" })">Titel Z-A</a>
                            <a class="dropdown-item" href="@Url.Action("Index", "Product", new { typeSort = "Price ASC" })">Preis: aufsteigend</a>
                            <a class="dropdown-item" href="@Url.Action("Index", "Product", new { typeSort = "Price DESC" })">Preis: absteigend</a>
                        </div>
                    </div>
                </td>
            </tr>
            
        </table>
        
    </div>
    <div class="col">
        <table class="table table-hover">
            @foreach (Product product in ViewBag.products)
            {
                <tr class="table-light">
                    <td>
                        <a href="@Url.Action("DetailView", "Product", new { id = product.Id })"><img src="~/Content/Images/@product.Photo" width="75" /></a>
                    </td>
                    <td>
                        <a href="@Url.Action("DetailView", "Product", new { id = product.Id })"><p class="lead">@product.Title</p></a>
                    </td>
                    <td>
                        <p class="text-warning">@product.Price €</p>
                    </td>
                    <td>
                        <a href="@Url.Action("Buy", "Cart", new { id = product.Id })">
                            <button type="button" class="btn btn-warning disabled">
                                Kaufen
                            </button>
                        </a>
                    </td>
                </tr>
            }
        </table>
</div>
</body>
</html>

MyBookstore/netzkern.MyBookstore.UI.Web.Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Der Buchladen - ASP.NET-Anwendung</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Der Buchladen</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarColor03">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link">
                        @Html.ActionLink("Home", "Index", "Home")
                        <span class="sr-only">(current)</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link">@Html.ActionLink("Produkte", "Index", "Product")</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link">@Html.ActionLink("Informationen", "About", "Home")</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link">@Html.ActionLink("Kontakt", "Contact", "Home")</a>
                </li>
            </ul>
            <ul class="navbar-nav mr-auto" aign="center">
                <li>
                    @if (Session["userId"] != null)
                    {
                        <p>Hallo @Session["userFirstName"] @Session["userLastName"]</p>
                    }
                </li>
            </ul>
            <ul class="navbar-nav mr-auto" aign="right">
                <li>
                    <a href="@Url.Action("Index", "Cart")">
                        <img src="~/Content/PicturesWebPage/cart.jpg" width="30" />
                    </a>
                </li>
                <li>
                    @if (Session["userId"] == null)
                    {
                        <a href="@Url.Action("Index", "SignIn")">
                            <img src="~/Content/PicturesWebPage/profile.png" width="30" />
                        </a>
                    }
                    else
                    {
                        <a href="@Url.Action("LogOut", "SignIn")">
                            <img src="~/Content/PicturesWebPage/LogOut.png" width="30" />
                        </a>
                    }
                </li>
            </ul>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Meine ASP.NET-Anwendung</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>